# Numpy Basics <hr style ="border:2.5px solid #964B00 "></hr>

Data Analyst: Sheny Uriza Mae C. Nardo <br>
Department: Electrical Engineering

In [7]:
# import and packages
import numpy as np
from scipy import stats

# 1D Array

In [10]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

# 2D Array

In [5]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [36]:
my_array = my_array.T

In [37]:
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
# add by row
np.sum(my_array,axis=0)

array([ 6, 15])

In [55]:
# by column
np.sum(my_array,axis=1)

array([5, 7, 9])

# Measures of Central Tendency

In [3]:
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [4]:
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [5]:
median_fruits = np.median(fruits)
median_fruits

np.float64(120.0)

In [9]:
mode_fruits = stats.mode(fruits)
mode_fruits

ModeResult(mode=np.int64(60), count=np.int64(1))

# Jaguar Vs Panther

Jaguar

In [10]:
jaguar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [13]:
jaguar_mean = np.mean(jaguar)
jaguar_mean

np.float64(9.399999999999999)

In [14]:
median_jaguar = np.median(jaguar)
median_jaguar

np.float64(9.8)

In [15]:
mode_jaguar = stats.mode(jaguar)
mode_jaguar

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [52]:
max_jag = np.max(jaguar)
min_jag = np.min(jaguar)
range_jag = max_jag - min_jag
range_jag

np.float64(8.0)

In [44]:
q1_jag = np.percentile(jaguar,25)
q1_jag

np.float64(9.4)

In [45]:
q2_jag = np.percentile(jaguar,50)
q2_jag

np.float64(9.8)

In [46]:
q3_jag = np.percentile(jaguar,75)
q3_jag

np.float64(10.45)

In [47]:
iqr_jag = q3_jag - q1_jag
iqr_jag

np.float64(1.049999999999999)

In [48]:
# sample variance
var_jag = np.var(jaguar,ddof=1)
var_jag

np.float64(4.86)

In [51]:
# sample standard deviation
std_jag = np.std(jaguar,ddof=1)
std_jag

np.float64(2.2045407685048604)

Panther

In [12]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [16]:
panther_mean = np.mean(panther)
panther_mean

np.float64(10.75)

In [17]:
median_panther = np.median(panther)
median_panther

np.float64(9.55)

In [18]:
mode_panther = stats.mode(panther)
mode_panther

ModeResult(mode=np.float64(9.1), count=np.int64(3))

In [57]:
max_pan = np.max(panther)
min_pan = np.min(panther)
range_pan = max_pan - min_pan
range_pan

np.float64(10.9)

In [59]:
q1_pan = np.percentile(panther,25)
q1_pan

np.float64(9.125)

In [61]:
q2_pan = np.percentile(panther,50)
q2_pan

np.float64(9.55)

In [60]:
q3_pan = np.percentile(panther,75)
q3_pan

np.float64(10.625)

In [62]:
iqr_pan = q3_pan - q1_pan
iqr_pan

np.float64(1.5)

In [63]:
# sample variance
var_pan = np.var(panther,ddof=1)
var_pan

np.float64(11.082777777777777)

In [64]:
# sample standard deviation
std_pan = np.std(panther,ddof=1)
std_pan

np.float64(3.3290806204983645)